image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: "v0.10.5"
  BUILDX_ARCH: "linux-amd64"

docker-build:
  before_script:
    - echo "$HUB_PASSWORD" | docker login --username
      $HUB_LOGIN --password-stdin
    - wget -O /usr/bin/docker-buildx
      https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.${BUILDX_ARCH}
    - chmod +x /usr/bin/docker-buildx
  script:
    - docker-buildx create --use
    - echo $CI_COMMIT_TAG > version
    - docker-buildx build
      --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      --tag marathonlabs/cli:latest
      --push
      .

