project_name: marathon-cloud
builds:
  - id: marathon-cloud
    binary: marathon-cloud
    main: dummy.go
    goos:
      # - darwin
      - linux
      # - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows 
        goarch: arm64
    hooks:
      # This is called for every architecture.
      # eg: ./build.sh linux_amd64 marathon-cloud
      post: 
        - ./build.sh "{{ .Target }}" "{{ .ProjectName }}"
universal_binaries:
- replace: true
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}_{{ .Arm }}{{ end }}-{{ .Summary }}"
    builds:
      - marathon-cloud
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
dockers:
- image_templates:
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "marathonlabs/{{ .ProjectName }}:latest-amd64"
  use: buildx
  goarch: amd64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- image_templates:
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - "marathonlabs/{{ .ProjectName }}:latest-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- image_templates:
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-armv6"
  - "marathonlabs/{{ .ProjectName }}:latest-armv6"
  use: buildx
  goarch: arm
  goarm: 6
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v6"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- image_templates:
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-armv7"
  - "marathonlabs/{{ .ProjectName }}:latest-armv7"
  use: buildx
  goarch: arm
  goarm: 7
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
- name_template: "marathonlabs/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-armv6"
  - "marathonlabs/{{ .ProjectName }}:{{ .Version }}-armv7"
- name_template: "marathonlabs/{{ .ProjectName }}:latest"
  image_templates:
  - "marathonlabs/{{ .ProjectName }}:latest-amd64"
  - "marathonlabs/{{ .ProjectName }}:latest-arm64v8"
  - "marathonlabs/{{ .ProjectName }}:latest-armv6"
  - "marathonlabs/{{ .ProjectName }}:latest-armv7"
checksum:
  name_template: 'checksums.txt'
release:
  disable: false
brews:
  - tap:
      owner: Malinskiy
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/MarathonLabs/marathon-cloud-cli"
    description: "Command-line interface for Marathon Cloud"
    license: "MIT"
    folder: Formula
