name: version-bump

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: >-
          JSON array of branches to target. The first branch in the array will
          be marked as the latest release.
        required: false
        type: string
        default: '["main"]'
permissions:
  contents: write
jobs:
  bump-version:
    strategy:
      matrix:
        target_branch: ${{ fromJSON(inputs.target_branch) }}
    runs-on: ubuntu-latest
    env:
      CARGO_EDIT_VERSION: 0.12.2
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo edit
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/cargo-edit
          key: cargo-edit-${{ env.CARGO_EDIT_VERSION }}
      - name: Add the tool cache directory to the search path
        run: echo "${{ runner.tool_cache }}/cargo-edit/bin/" >>$GITHUB_PATH
      - name: Ensure cargo-edit is installed
        run: |
          cargo install \
            --root ${{ runner.tool_cache }}/cargo-edit \
            --version ${{ env.CARGO_EDIT_VERSION }} \
            cargo-edit
      - run: cargo set-version --bump patch
      - run: git diff
      - name: Push changes
        run: |
          git config --global user.name 'Anton Malinlskiy'
          git config --global user.email 'malinskiy@users.noreply.github.com'
          git commit -am "Automated patch version bump"
          git push
